Resources:

  DynamoTableEvents:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: ${self:service}-${sls:stage}-events
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: True
      Tags: 
        - Key: service
          Value: joinme-${sls:stage}-events
        - Key: app
          Value: ${self:service}
