name: Release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          "@semantic-release/commit-analyzer@8.0.1"
          "@semantic-release/release-notes-generator@9.0.3"
          "@semantic-release/git@9.0.1"
          "@semantic-release/github@7.2.3"
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
